name: Package
on:
  push:
    branches:
      - main
jobs:
  create_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Create Package
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pyinstaller
          pyinstaller src/engine.py --name HivemindEngine --noconsole --onefile

  upload_package:
    runs-on: ubuntu-latest
    needs: create_package
    steps:
      - name: Upload Package
        run: |
          echo "Package upload logic here"
