name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version number
        required: true
      disable_checks:
        type: boolean
        description: Disable version consistency checks
        default: false

jobs:
  version-validation:
    permissions:
      contents: read
    uses: crystal-nest/.github/.github/workflows/version_validation.yml@main
    with:
      version: ${{ github.event.inputs.version }}
      disable_checks: ${{ github.event.inputs.disable_checks }}
    secrets: inherit

  build:
    needs: version-validation
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    needs: build
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml
    secrets: inherit

  verify:
    needs: test
    permissions:
      contents: read
    uses: ./.github/workflows/verify.yml
    secrets: inherit
