name: Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    uses: ./.github/workflows/build.yml
    secrets: inherit
    steps:
      - name: Unit Tests
        run: pytest test/
