name: Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/workflows/build.yml

      - name: Unit Tests
        run: pytest test/
