name: Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
      - uses: ./.github/workflows/build.yml

      - name: Unit Tests
        run: pytest test/
