name: Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  call-build:
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        run: pytest test/
